### ISSUE TITLE
.word in data section does not store value on a word boundary

### ISSUE THREAD

**Issue by weiwenzhou** [kevintmcdonnell/STARS#1]
OS: Windows
Ran in: Git Bash and Windows Powershell

.word values are not stored on word boundaries leading to MemoryAlignmentError: 0x10010003 is not word aligned.

```
.data
arg0: .ascii "123" # replacing "123" with "1234" works
arg1: .word 3
.text
.globl main
main:
la $a0, arg0
lw $a2, arg2 # error at this line
li $v0, 10
syscall
```

**Comment by ipeitzsch** [comment]
This is intentional. STARS does not auto-align, and arg0 is only 3 bytes. To get arg1 on the proper alignment you must add the space yourself or use the .align directive.
